

services:
  mongo:
    image: mongo:6
    container_name: alarma-mongo
    restart: always
    volumes:
      - mongo_data:/data/db
    ports:
      - "27018:27017"

  backend:
    build: ./backend-alarmas
    container_name: alarma-backend
    restart: always
    env_file:
      - .env
    depends_on:
      - mongo
    ports:
      - "12081:3000"

  docs:
    build: ./mi-documentacion
    container_name: alarma-docs
    restart: always
    ports:
      - "12082:80"    

  frontend:
    build: ./frontend-alarmas
    container_name: alarma-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "12080:80"

volumes:
  mongo_data:
